# Generated by Django 6.0.5 on 2026-06-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_rating_profile_tags_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tags',
            new_name='hobbies',
        ),
    ]
