# Generated by Django 6.0.6 on 2026-06-15 04:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_profile_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="trips_completed",
        ),
    ]
