# Generated by Django 6.0.6 on 2026-06-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_trips_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='travel_bio',
            field=models.TextField(blank=True),
        ),
    ]
