# Generated by Django 6.0.6 on 2026-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
