# Generated by Django 6.0.6 on 2026-07-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_notification_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="instagram",
            field=models.URLField(blank=True),
        ),
    ]
