# Generated by Django 6.0.6 on 2026-07-22 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_savedplace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedplace",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_places",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
