# Generated by Django 6.0.5 on 2026-06-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0003_trip_completed_trip_created_at_trip_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
