# Generated by Django 6.0.5 on 2026-06-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0004_trip_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="slots_available",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
