# Generated by Django 6.0.5 on 2026-06-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0005_alter_trip_slots_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="slots_available",
            field=models.PositiveIntegerField(),
        ),
    ]
