# Generated by Django 6.0.5 on 2026-06-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0007_alter_trip_duration_alter_trip_from_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripmembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Onboard"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
