# Generated by Django 6.0.5 on 2026-06-04 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_alter_tripmembership_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tripmembership',
            unique_together={('trip', 'user')},
        ),
    ]
