# Generated by Django 6.0.5 on 2026-06-04 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0009_alter_tripmembership_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tripmembership",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="tripmembership",
            constraint=models.UniqueConstraint(
                fields=("trip", "user"), name="unique_trip_user"
            ),
        ),
    ]
