# Generated by Django 6.0.5 on 2026-06-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_remove_tripgroup_id_tripgroup_trip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripgroupmessage',
            old_name='created_at',
            new_name='send_at',
        ),
        migrations.RenameField(
            model_name='tripgroupmessage',
            old_name='user',
            new_name='sender',
        ),
    ]
