# Generated by Django 6.0.5 on 2026-06-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0014_rename_created_at_tripgroupmessage_send_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripgroup",
            name="activity",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
