# Generated by Django 6.0.5 on 2026-06-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0015_tripgroup_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tripgroup",
            name="activity",
        ),
        migrations.AddField(
            model_name="tripgroupmessage",
            name="activity",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tripgroupmessage",
            name="is_system_message",
            field=models.BooleanField(default=False),
        ),
    ]
