# Generated by Django 6.0.6 on 2026-06-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0018_trip_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="completed",
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("upcoming", "Upcoming"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                ],
                default="planning",
                max_length=20,
            ),
        ),
    ]
