# Generated by Django 6.0.6 on 2026-06-22 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0025_tripmembership_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="expected_arrival_time",
            new_name="expected_finish_time",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="duration_unit",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="duration_value",
        ),
    ]
