# Generated by Django 6.0.6 on 2026-06-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0026_rename_expected_arrival_time_trip_expected_finish_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='orgin_lat',
            new_name='origin_lat',
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('ride-sharing', 'Ride Sharing'), ('trip', 'Trip')], default='trip', max_length=20),
        ),
    ]
