# Generated by Django 6.0.6 on 2026-06-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0028_alter_trip_departure_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripgroup',
            name='whats_app_group_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
