# Generated by Django 6.0.6 on 2026-07-17 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0031_place_remove_activity_place_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food & Drinks'), ('sightseeing', 'Sightseeing'), ('nature', 'Nature & Outdoors'), ('shopping', 'Shopping'), ('entertainment', 'Entertainment'), ('sports', 'Sports & Adventure'), ('nightlife', 'Nightlife'), ('relaxation', 'Relaxation'), ('stay', 'Stay'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='rides.place'),
        ),
    ]
