# Generated by Django 6.0.6 on 2026-07-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0033_place_name_place_primary_type_alter_activity_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='photos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
