# Generated by Django 6.0.6 on 2026-07-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0034_place_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
