# Generated by Django 6.0.6 on 2026-07-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0035_place_map_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
