# Generated by Django 6.0.6 on 2026-07-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0036_place_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='discoverable',
            field=models.BooleanField(default=False),
        ),
    ]
