# Generated by Django 6.0.6 on 2026-07-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0037_place_discoverable"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
