# Generated by Django 6.0.6 on 2026-07-26 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0038_place_featured"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="discoverable",
        ),
    ]
