# Generated by Django 6.0.6 on 2026-07-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0039_remove_place_discoverable"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="best_for",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="place",
            name="best_time_to_visit",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="place",
            name="highlights",
            field=models.TextField(blank=True),
        ),
    ]
