# Generated by Django 6.0.6 on 2026-07-27 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0040_place_best_for_place_best_time_to_visit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="primary_type",
            new_name="types",
        ),
        migrations.RemoveField(
            model_name="place",
            name="photos",
        ),
    ]
