# Generated by Django 6.0.6 on 2026-08-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0041_rename_primary_type_place_types_remove_place_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="user_rating_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
