# Generated by Django 6.0.6 on 2026-08-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0042_place_rating_place_user_rating_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="place",
            name="user_rating_count",
        ),
        migrations.AddField(
            model_name="activity",
            name="activity_image",
            field=models.ImageField(
                blank=True,
                default="activity_images/default_activity.jpg",
                null=True,
                upload_to="activity_images/",
            ),
        ),
    ]
