# Generated by Django 6.0.6 on 2026-08-02 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0043_remove_place_rating_remove_place_user_rating_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
