# Generated by Django 6.0.6 on 2026-08-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0044_activity_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
