# Generated by Django 6.0.6 on 2026-08-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0045_activity_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="region",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
