# Generated by Django 6.0.6 on 2026-08-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0046_place_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="activity_images/"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("food", "Food & Drinks"),
                    ("sightseeing", "Sightseeing"),
                    ("nature", "Nature & Outdoors"),
                    ("shopping", "Shopping"),
                    ("entertainment", "Entertainment"),
                    ("sports", "Sports & Adventure"),
                    ("nightlife", "Nightlife"),
                    ("relaxation", "Relaxation"),
                    ("stay", "Stay"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
                null=True,
            ),
        ),
    ]
