# Generated by Django 6.0.6 on 2026-08-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0047_alter_activity_activity_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="viewport_high_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="viewport_high_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="viewport_low_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="viewport_low_lng",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
