# Generated by Django 6.0.6 on 2026-08-05 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0048_place_viewport_high_lat_place_viewport_high_lng_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="title",
            new_name="name",
        ),
    ]
